# Config file for Air
[build]
bin = "bin/main"
cmd = "go build -o ./bin/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "bin"]
exclude_file = ["air.conf"]
exclude_regex = ["_test.go"]
follow_symlink = true
full_bin = "APP_ENV=dev APP_USER=air ./bin/main"
kill_delay = 500
log = "air.log"
main = "main.go"
tmp_dir = "tmp"
watch_dir = ["."]